
name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: "sudo apt-get install cppcheck; sudo apt-get install valgrind"
    - name: cppcheck
      run: "cd work; make cppcheck"
    - name: make
      run: "cd work; make"
    - name: valgrind
      run: "cd work; make valgrind"
    - name: sanitizer
      run: "cd work; make sanitizer"
    - name: gcov
      run: "cd work; make gcov"